engines:
  cppcheck:
    enabled: true
    config:
      check: all
      project: compile_commands.json
      language: c++
      stds:
        - c++11
      platform: unix64
      defines:
        - "DEBUG=1"
        - "__cplusplus"
      undefines:
        - include/
      max_configs: 42
      inconclusive: false
