sudo: true

language:
  - cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

script:
  - make
  - ./unit-test

after_success:
  - coveralls --exclude test --exclude external --gcov-options '\-lp'

notifications:
  email: false
