sudo: true

language:
  - cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get install -y lcov
  - gen install coveralls-lcov
  - pip install --user cpp-coveralls
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

script:
  - make
  - ./unit-test

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' 'external/*' --output-file coveragw.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS} coverage.info

notifications:
  email: false
